# Generated by Django 5.2.4 on 2025-07-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pass1', models.CharField(max_length=128)),
                ('pass2', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FarmProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_category', models.CharField(choices=[('fruit', 'Fruit'), ('grains', 'Grains'), ('vegetables', 'Vegetables'), ('legumes', 'Legumes'), ('nuts', 'Nuts & Seeds'), ('spices', 'Spices & Herbs'), ('beverages', 'Beverages'), ('others', 'Others')], max_length=50)),
                ('product_description', models.CharField(max_length=50)),
            ],
        ),
    ]
