# Generated by Django 5.2.4 on 2025-07-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarket', '0002_farmproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='product_category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('grains', 'Grains'), ('vegetables', 'Vegetables'), ('legumes', 'Legumes'), ('nuts', 'Nuts & Seeds'), ('spices', 'Spices & Herbs'), ('beverages', 'Beverages'), ('others', 'Others')], max_length=50),
        ),
    ]
