# Generated by Django 5.2.4 on 2025-07-16 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarket', '0002_farmermodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer')], default='buyer', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('grain', 'Grain'), ('vegetable', 'Vegetable'), ('legume', 'Legume'), ('spice', 'Spice'), ('nut', 'Nuts & Seeds'), ('beverage', 'Beverage'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FarmProduct',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='farmermodel',
            name='pass2',
        ),
        migrations.AddField(
            model_name='farmermodel',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='farmermodel',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer')], default='farmer', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenmarket.farmermodel'),
        ),
    ]
