# Generated by Django 5.2.4 on 2025-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenmarket', '0003_buyermodel_product_delete_farmproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='productIMG/'),
        ),
    ]
